baseURL: 'https://stellular-axolotl-9c709c.netlify.app/'
languageCode: en-us
title: Apsho | App landing template
theme: apsho
menu:
  main:
    - name: About
      url: '#about'
      weight: 1
    - name: Docs
      url: '#docs'
      weight: 2
    - name: Pricing
      url: '#pricing'
      weight: 3
    - name: Contact Us
      url: '#contact'
      weight: 4
  sitemap:
    - name: Home
      url: '#'
      weight: 1
    - name: Latest Article
      url: /blog
      weight: 2
    - name: Privacy & Policy
      url: /privacy
      weight: 3
    - name: Contact
      url: /contact
      weight: 4
params:
  address:
    address: '23 Khan Niketon, Grand Street, NYK.'
    email: apsho@example.com
    phone: +(448) 833 5272 332
  social:
    facebook: 'https://www.facebook.com/pg/staticmania'
    twitter: 'https://twitter.com/static_mania'
    github: 'https://github.com/StaticMania'
  logo: images/header/logo-part1.svg
  formspreeURL: 'https://formspree.io/mjvankow'
  googleAnalytics: UA-175025671-2
  footerTitle: Get the latest app updates
  copyright1: All right reserved
  copyright2: Copyright © Apsho 2020
  email: help@staticmania.com
